/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 rocket9.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/rocket9.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rocket.geometry} material={materials['Rocket.003']} position={[95.449, -1.116, 63.512]} />
    </group>
  )
}

useGLTF.preload('/rocket9.glb')
